<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Calendar_event extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Calendar_event_model');
    } 

    /*
     * Listing of calendar_events
     */
    function index()
    {
        $data['calendar_events'] = $this->Calendar_event_model->get_all_calendar_events();
        
        $data['_view'] = 'calendar_event/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new calendar_event
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'shipment_id' => $this->input->post('shipment_id'),
				'md5_container_number_and_date' => $this->input->post('md5_container_number_and_date'),
				'title' => $this->input->post('title'),
				'event_type' => $this->input->post('event_type'),
				'start' => $this->input->post('start'),
				'end' => $this->input->post('end'),
				'description' => $this->input->post('description'),
            );
            
            $calendar_event_id = $this->Calendar_event_model->add_calendar_event($params);
            redirect('calendar_event/index');
        }
        else
        {
			$this->load->model('Shipment_model');
			$data['all_shipments'] = $this->Shipment_model->get_all_shipments();
            
            $data['_view'] = 'calendar_event/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a calendar_event
     */
    function edit($ID)
    {   
        // check if the calendar_event exists before trying to edit it
        $data['calendar_event'] = $this->Calendar_event_model->get_calendar_event($ID);
        
        if(isset($data['calendar_event']['ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'shipment_id' => $this->input->post('shipment_id'),
					'md5_container_number_and_date' => $this->input->post('md5_container_number_and_date'),
					'title' => $this->input->post('title'),
					'event_type' => $this->input->post('event_type'),
					'start' => $this->input->post('start'),
					'end' => $this->input->post('end'),
					'description' => $this->input->post('description'),
                );

                $this->Calendar_event_model->update_calendar_event($ID,$params);            
                redirect('calendar_event/index');
            }
            else
            {
				$this->load->model('Shipment_model');
				$data['all_shipments'] = $this->Shipment_model->get_all_shipments();

                $data['_view'] = 'calendar_event/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The calendar_event you are trying to edit does not exist.');
    } 

    /*
     * Deleting calendar_event
     */
    function remove($ID)
    {
        $calendar_event = $this->Calendar_event_model->get_calendar_event($ID);

        // check if the calendar_event exists before trying to delete it
        if(isset($calendar_event['ID']))
        {
            $this->Calendar_event_model->delete_calendar_event($ID);
            redirect('calendar_event/index');
        }
        else
            show_error('The calendar_event you are trying to delete does not exist.');
    }
    
}
