<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        
    }

    function index()
    {
		if (!$this->session->userdata('logged_in')) {
            redirect('users/login');
        }
        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
    }
}
