<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Product extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Product_model');
    } 

    /*
     * Listing of products
     */
    function index()
    {
        $data['products'] = $this->Product_model->get_all_products();
        
        $data['_view'] = 'product/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new product
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'product_name' => $this->input->post('product_name'),
            );
            
            $product_id = $this->Product_model->add_product($params);
            redirect('product/index');
        }
        else
        {            
            $data['_view'] = 'product/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a product
     */
    function edit($id)
    {   
        // check if the product exists before trying to edit it
        $data['product'] = $this->Product_model->get_product($id);
        
        if(isset($data['product']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'product_name' => $this->input->post('product_name'),
                );

                $this->Product_model->update_product($id,$params);            
                redirect('product/index');
            }
            else
            {
                $data['_view'] = 'product/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The product you are trying to edit does not exist.');
    } 

    /*
     * Deleting product
     */
    function remove($id)
    {
        $product = $this->Product_model->get_product($id);

        // check if the product exists before trying to delete it
        if(isset($product['id']))
        {
            $this->Product_model->delete_product($id);
            redirect('product/index');
        }
        else
            show_error('The product you are trying to delete does not exist.');
    }
    
}
