<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Trucker extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Trucker_model');
    } 

    /*
     * Listing of truckers
     */
    function index()
    {
        $data['truckers'] = $this->Trucker_model->get_all_truckers();
        
        $data['_view'] = 'trucker/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new trucker
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'trucker_name' => $this->input->post('trucker_name'),
            );
            
            $trucker_id = $this->Trucker_model->add_trucker($params);
            redirect('trucker/index');
        }
        else
        {            
            $data['_view'] = 'trucker/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a trucker
     */
    function edit($id)
    {   
        // check if the trucker exists before trying to edit it
        $data['trucker'] = $this->Trucker_model->get_trucker($id);
        
        if(isset($data['trucker']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'trucker_name' => $this->input->post('trucker_name'),
                );

                $this->Trucker_model->update_trucker($id,$params);            
                redirect('trucker/index');
            }
            else
            {
                $data['_view'] = 'trucker/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The trucker you are trying to edit does not exist.');
    } 

    /*
     * Deleting trucker
     */
    function remove($id)
    {
        $trucker = $this->Trucker_model->get_trucker($id);

        // check if the trucker exists before trying to delete it
        if(isset($trucker['id']))
        {
            $this->Trucker_model->delete_trucker($id);
            redirect('trucker/index');
        }
        else
            show_error('The trucker you are trying to delete does not exist.');
    }
    
}
