<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Update_event extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Update_event_model');
    } 

    /*
     * Listing of update_events
     */
    function index()
    {
        $data['update_events'] = $this->Update_event_model->get_all_update_events();
        
        $data['_view'] = 'update_event/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new update_event
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'time_and_date' => $this->input->post('time_and_date'),
				'container_number' => $this->input->post('container_number'),
				'content' => $this->input->post('content'),
            );
            
            $update_event_id = $this->Update_event_model->add_update_event($params);
            redirect('update_event/index');
        }
        else
        {            
            $data['_view'] = 'update_event/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a update_event
     */
    function edit($id)
    {   
        // check if the update_event exists before trying to edit it
        $data['update_event'] = $this->Update_event_model->get_update_event($id);
        
        if(isset($data['update_event']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'time_and_date' => $this->input->post('time_and_date'),
					'container_number' => $this->input->post('container_number'),
					'content' => $this->input->post('content'),
                );

                $this->Update_event_model->update_update_event($id,$params);            
                redirect('update_event/index');
            }
            else
            {
                $data['_view'] = 'update_event/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The update_event you are trying to edit does not exist.');
    } 

    /*
     * Deleting update_event
     */
    function remove($id)
    {
        $update_event = $this->Update_event_model->get_update_event($id);

        // check if the update_event exists before trying to delete it
        if(isset($update_event['id']))
        {
            $this->Update_event_model->delete_update_event($id);
            redirect('update_event/index');
        }
        else
            show_error('The update_event you are trying to delete does not exist.');
    }
    
}
