<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Datatables_state_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get datatables_state by id
     */
    function get_datatables_state($id)
    {
        return $this->db->get_where('datatables_states',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all datatables_states
     */
    function get_all_datatables_states()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('datatables_states')->result_array();
    }
        
    /*
     * function to add new datatables_state
     */
    function add_datatables_state($params)
    {
        $this->db->insert('datatables_states',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update datatables_state
     */
    function update_datatables_state($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('datatables_states',$params);
    }
    
    /*
     * function to delete datatables_state
     */
    function delete_datatables_state($id)
    {
        return $this->db->delete('datatables_states',array('id'=>$id));
    }
}
