<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Shipment_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get shipment by id
     */
    function get_shipment($id)
    {
        return $this->db->get_where('shipments',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all shipments
     */
    function get_all_shipments()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('shipments')->result_array();
    }
        
    /*
     * function to add new shipment
     */
    function add_shipment($params)
    {
        $this->db->insert('shipments',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update shipment
     */
    function update_shipment($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('shipments',$params);
    }
    
    /*
     * function to delete shipment
     */
    function delete_shipment($id)
    {
        return $this->db->delete('shipments',array('id'=>$id));
    }
}
