<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Trucker_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get trucker by id
     */
    function get_trucker($id)
    {
        return $this->db->get_where('truckers',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all truckers
     */
    function get_all_truckers()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('truckers')->result_array();
    }
        
    /*
     * function to add new trucker
     */
    function add_trucker($params)
    {
        $this->db->insert('truckers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update trucker
     */
    function update_trucker($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('truckers',$params);
    }
    
    /*
     * function to delete trucker
     */
    function delete_trucker($id)
    {
        return $this->db->delete('truckers',array('id'=>$id));
    }
}
