<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Update_event_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get update_event by id
     */
    function get_update_event($id)
    {
        return $this->db->get_where('update_events',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all update_events
     */
    function get_all_update_events()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('update_events')->result_array();
    }
        
    /*
     * function to add new update_event
     */
    function add_update_event($params)
    {
        $this->db->insert('update_events',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update update_event
     */
    function update_update_event($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('update_events',$params);
    }
    
    /*
     * function to delete update_event
     */
    function delete_update_event($id)
    {
        return $this->db->delete('update_events',array('id'=>$id));
    }
}
