<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vendor_product_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get vendor_product by id
     */
    function get_vendor_product($id)
    {
        return $this->db->get_where('vendor_products',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all vendor_products
     */
    function get_all_vendor_products()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('vendor_products')->result_array();
    }
        
    /*
     * function to add new vendor_product
     */
    function add_vendor_product($params)
    {
        $this->db->insert('vendor_products',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update vendor_product
     */
    function update_vendor_product($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('vendor_products',$params);
    }
    
    /*
     * function to delete vendor_product
     */
    function delete_vendor_product($id)
    {
        return $this->db->delete('vendor_products',array('id'=>$id));
    }
}
