<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vendor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get vendor by id
     */
    function get_vendor($id)
    {
        return $this->db->get_where('vendors',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all vendors
     */
    function get_all_vendors()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('vendors')->result_array();
    }
        
    /*
     * function to add new vendor
     */
    function add_vendor($params)
    {
        $this->db->insert('vendors',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update vendor
     */
    function update_vendor($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('vendors',$params);
    }
    
    /*
     * function to delete vendor
     */
    function delete_vendor($id)
    {
        return $this->db->delete('vendors',array('id'=>$id));
    }
}
