<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vendor_document_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get vendor_document by id
     */
    function get_vendor_document($id)
    {
        return $this->db->get_where('vendor_documents',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all vendor_documents
     */
    function get_all_vendor_documents()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('vendor_documents')->result_array();
    }
        
    /*
     * function to add new vendor_document
     */
    function add_vendor_document($params)
    {
        $this->db->insert('vendor_documents',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update vendor_document
     */
    function update_vendor_document($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('vendor_documents',$params);
    }
    
    /*
     * function to delete vendor_document
     */
    function delete_vendor_document($id)
    {
        return $this->db->delete('vendor_documents',array('id'=>$id));
    }
}
